version: '3.2'
services:
    backend:
        image: backend  
        container_name: backend
        # env_file: ./.env
        environment:
          - DB_NAME='plan'
          - DB_HOST='127.0.0.1'
          - DB_USER='root'
          - DB_PASS='t52045204'

        volumes:
          - /usr/src/app
        ports:
            - "4000:4000"
        depends_on:
            - mysql
        command: "yarn start"
    # frontend:
    #     image: react-frontend  
    #     container_name: frontend
    #     # env_file: ./.env
    #     environment:
    #         - DB_NAME='plan'
    #         - DB_HOST='0.0.0.0'
    #         - DB_USER='root'
    #         - DB_PASS='t52045204'

    #     volumes:
    #         - /usr/src/app
    #     ports:
    #         - "4000:4000"
    #     depends_on:
    #         - mysql
    #     command: "yarn start"
        
    mysql:
        image: mysql
        container_name: mysqldatabase
        ports:
            - "3333:3306"
        environment:
            
            MYSQL_ROOT_PASSWORD: 't52045204'
            
    
            MYSQL_DATABASE: 'plan'
            MYSQL_ROOT_HOST: '127.0.0.1'
        # command: mysqladmin create testing_db
        volumes:
          - ./sql:/docker-entrypoint-initdb.d
            