version: '3.2'
services:
    backend:
        image: backend  
        container_name: backend
        # env_file: ./.env
        environment:
          - DB_NAME=plan
          - DB_HOST=mysql
          - DB_USER=root
          - DB_PASS=t52045204
        #   - DB_PORT=3306

        volumes:
          - /usr/src/app
        ports:
            - "4000:4000"
        depends_on:
            - mysql
        command: "yarn start"

        
    mysql:
        image: mysql
        container_name: mysql
        ports:
            - "3333:3306"
        environment:
            
            MYSQL_ROOT_PASSWORD: t52045204
            MYSQL_DATABASE: plan
            # MYSQL_ROOT_HOST: '0.0.0.0'
        command: --default-authentication-plugin=mysql_native_password
        volumes:
          - ./sql:/docker-entrypoint-initdb.d
            